chore: make owlbot check required
googleapis/java-bigtable pull request #1096
Opened 2021-12-07 16:58 UTC by Neenu1995

2021-12-07 17:11 UTC, Neenu1995 commented
Merge after owlbot migration PR is merged.

2021-12-07 17:23 UTC, eaball35 approved these changes

2022-01-13 18:48 UTC, kolea2 requested changes

2022-01-13 18:48 UTC, kolea2 commented on .github/sync-repo-settings.yaml
> +      - OwlBot Post Processor
lgtm, but want to hold off a day or two just to make sure we didn't mess anything up with merging in the migration PR :)

2022-01-19 15:15 UTC, kolea2 approved these changes

2022-01-19 15:15 UTC, merged