feat: implement cross-project table restore and integration testing
googleapis/java-bigtable pull request #1289
Opened 2022-06-28 17:51 UTC by rafitj

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2022-06-30 13:50 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequest.java
> +   * instance and project as the destination table. To restore a table from a backup in another instance, use
Add a comment:

"To restore a table from a backup in another project, use ..."

2022-06-30 13:50 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequest.java
> +   * different instance but the same project as the destination table. To restore a table from a backup in another project, use
I think you'll need to reformat the comment here by running: `mvn com.coveo:fmt-maven-plugin:format`

2022-07-06 15:19 UTC, mutianf approved these changes

2022-07-06 15:33 UTC, kolea2 requested changes
There should be some tests added here: https://github.com/googleapis/java-bigtable/blob/main/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTests.java#L584

2022-11-29 20:37 UTC, kolea2 approved these changes

2022-12-05 19:31 UTC, closed without merging