feat: Add simple implementation of RateLimitingCallable
googleapis/java-bigtable pull request #1510
Opened 2022-11-10 18:19 UTC by diegomez17

2022-11-23 20:28 UTC, mutianf requested changes
I haven't looked at the tests yet. But please make sure you don't merge this pr into the main branch, update the pr to merge into a private branch.

2022-11-23 20:28 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RateLimitingServerStreamingCallable.java
> +public class RateLimitingServerStreamingCallable<RequestT, ResponseT>
I'm not sure if metrics/ is the right place for this class. Maybe you can just move it under stub/.

2022-11-23 20:28 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
> +  public EnhancedBigtableStub(EnhancedBigtableStubSettings settings, ClientContext clientContext, RateLimitingStats rateLimitingStats) {
If you move the RateLimitingCallable and RateLimitingCallableTests under stub/ you won't need to make this class public.

2022-11-23 20:28 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
> +    //if (settings.bulkMutateRowsSettings().isCpuBasedThrottlingEnabled()) {
why is this check commented out?

2022-11-23 20:28 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RateLimitingServerStreamingCallable.java
> +      // What process do we need to get this proto?
I'm not sure if we want to publish the protos just yet. So I think manually adding the generated classes here is good for now.

2022-11-23 20:28 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
> +  static final Metadata.Key<String> CPU_THROTTLE_HEADER_KEY =
I think this can be removed now

2022-11-23 20:28 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
> +  static double calculateQpsChange(double[] tsCpus, double target, double currentRate) {
I'm not sure if this method fits here, maybe it can be a private method in RateLimitingStats

2022-12-01 21:59 UTC, diegomez17 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/RateLimitingServerStreamingCallable.java
> +    //if (context.getOption(Util.GRPC_METADATA) == null) { // get metadata?
Some will stay, but will be removed when closer to jar and delivery.

2023-01-13 22:21 UTC, closed without merging