fix: remove grpclb
googleapis/java-bigtable pull request #2033
Opened 2023-12-18 21:34 UTC by mohanli-ml

Remove attempt DirectPath gRPCLB by default in CBT Java because:
1. gRPCLB is being deprecated, and CBT has removed all the gRPCLB traffic back to CloudPath;
2. Attempt gRPCLB by default has known DNS amplifying issue, https://github.com/googleapis/google-cloud-go/issues/7812.

2023-12-18 21:48 UTC, igorbernstein2 approved these changes

2024-04-17 18:14 UTC, mohanli-ml commented
Friendly ping. Can we merge this PR? Golang has merged https://github.com/googleapis/google-cloud-go/pull/9186 so I want  to make sure Java and Go has the same behavior. Thanks!

2024-04-19 19:53 UTC, igorbernstein2 approved these changes

2024-04-19 19:54 UTC, igorbernstein2 requested changes
Also, please remove this line:
https://github.com/googleapis/java-bigtable/blob/main/google-cloud-bigtable/pom.xml#L714

2024-04-19 21:15 UTC, mohanli-ml commented
> Also, please remove this line: https://github.com/googleapis/java-bigtable/blob/main/google-cloud-bigtable/pom.xml#L714

Done. Thanks Igor!

2024-05-11 13:53 UTC, igorbernstein2 approved these changes

2024-06-25 14:15 UTC, merged