feat: migrate to OTEL and enable metrics by default
googleapis/java-bigtable pull request #2166
Opened 2024-03-13 01:31 UTC by mutianf

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Rollback plan is reviewed and LGTMed
- [ ] All new data plane features have a completed end to end testing plan

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2024-03-15 14:39 UTC, rkaregar approved these changes

2024-03-18 16:00 UTC, igorbernstein2 requested changes

2024-03-18 19:21 UTC, mutianf commented on google-cloud-bigtable-deps-bom/pom.xml
> +        <version>1.34.1</version>
I can't bump the version until we pick up the latest version bump in the shared libraries

2024-03-18 19:36 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
> +      credentialsProvider = FixedCredentialsProvider.create(credentials);
Hmm I don't think this works?

2024-04-02 19:10 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
> +      credentialsProvider = FixedCredentialsProvider.create(credentials);
?

2024-04-02 19:13 UTC, igorbernstein2 approved these changes

2024-04-12 13:58 UTC, mutianf commented
/gcbrun

2024-04-12 14:09 UTC, merged