fix: support override monitoring endpoint
googleapis/java-bigtable pull request #2364
Opened 2024-09-28 00:54 UTC by mutianf

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Rollback plan is reviewed and LGTMed
- [ ] All new data plane features have a completed end to end testing plan

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2024-09-30 16:45 UTC, igorbernstein2 requested changes

2024-09-30 16:45 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
> +    public Builder setMetricsEndpoint(String endpoint) {
This needs a bit more documentation and be more explicit that this is for the builtin metrics

2024-09-30 16:45 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
> +    public String getMetricsEndpoint() {
please be more explicit that this is for built in metrics

2024-09-30 17:04 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
> +    settingsBuilder.setEndpoint(endpoint);
Currently we use it in our test environment to write to the test endpoint. I was debating if we want to keep it. Not sure if anyone ever discovered this and started using it.

2024-09-30 17:04 UTC, mutianf commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsView.java
> +        projectId, credentials, builder, MetricServiceSettings.getDefaultEndpoint());
This was the behavior we had in BigtableCloudMonitoringExporter. Whats the resolved universe endpoint?

2024-09-30 21:04 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
>    private static final String MONITORING_ENDPOINT =
This is a bit confusing now - its no longer the monitoring endpoint, but a monitoring endpoint override from sys prop. How about `MONITORING_ENDPOINT_OVERRIDE_SYS_PROP`?

2024-09-30 21:04 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
>    private static final String MONITORING_ENDPOINT =
Also mark it as Nullable and deprecated

2024-09-30 21:06 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsView.java
> +        projectId, credentials, builder, MetricServiceSettings.getDefaultEndpoint());
MetricServiceSettings.getDefaultEndpoint() - should this be null to flag default value?

2024-10-01 01:32 UTC, igorbernstein2 approved these changes

2024-10-01 01:32 UTC, merged