fix: allow factory to export to different projects
googleapis/java-bigtable pull request #2374
Opened 2024-10-08 14:01 UTC by mutianf

This fix removed the check on Bigtable project id and gets the BigtableTable resource project id directly from metrics attribute. BigtableDataClientFactory can create one client for multiple projects. Removing the check allows people using BigtableDataClientFactory to export to different projects.

2024-10-16 16:54 UTC, igorbernstein2 requested changes
also, this needs a test :)

2024-10-16 16:54 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
> +      @Nullable Credentials credentials, @Nullable String endpoint) throws IOException {
Im a lil concerned about the remaining args here - like the problematic projectId, they are used to construct a singleton, but not consulted when getting existing instances of the singleton. What happens if someone constructs 2 clients with a different set of creds?

2024-10-16 16:54 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableCloudMonitoringExporter.java
> +    Map<String, List<TimeSeries>> bigtableTimeSeries;
please add a comment what the key is

2024-10-16 16:54 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableExporterUtils.java
> +  static Map<String, List<TimeSeries>> convertToBigtableTimeSeries(
docs for what the key is here

2024-11-04 19:02 UTC, mutianf commented
Note: global otel is not idea. We should refactor how the client context is created so otel doesn't need to be global.

2024-11-27 15:00 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
> +  public OpenTelemetry createOpenTelemetry() {
this doesnt look like it creates anything :)

2024-11-27 15:02 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableClientContext.java
> +      errorCountPerConnectionMetricTracker =
is it possible to factor this out to a helper method?

2024-11-27 15:03 UTC, igorbernstein2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java
>                .setTracerFactory(
does the TracerFactory need to be overwritten for the default case?

2024-12-02 21:14 UTC, merged