feat: Implement toString for Bigtable*Settings
googleapis/java-bigtable pull request #488
Opened 2020-10-22 11:27 UTC by dmitry-fa

Example of output from toString():

```
BigtableInstanceAdminSettings{
projectId=our-project-212, 
createInstanceSettings=UnaryCallSettings{retryableCodes=[], retrySettings=RetrySettings{totalTimeout=PT5M, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT0S, maxAttempts=0, jittered=true, 
initialRpcTimeout=PT5M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT5M}},
createInstanceOperationSettings=com.google.api.gax.rpc.OperationCallSettings@3796751b,
getInstanceSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M,
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}},
listInstancesSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE],
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
partialUpdateInstanceSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
partialUpdateInstanceOperationSettings=com.google.api.gax.rpc.OperationCallSettings@67b64c45, 
deleteInstanceSettings=UnaryCallSettings{retryableCodes=[], retrySettings=RetrySettings{totalTimeout=PT1M, 
initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT0S, maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, 
rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, createClusterSettings=UnaryCallSettings{retryableCodes=[], 
retrySettings=RetrySettings{totalTimeout=PT1M, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT0S, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
createClusterOperationSettings=com.google.api.gax.rpc.OperationCallSettings@4411d970, 
getClusterSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
listClustersSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
updateClusterSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
updateClusterOperationSettings=com.google.api.gax.rpc.OperationCallSettings@6442b0a6, 
deleteClusterSettings=UnaryCallSettings{retryableCodes=[], retrySettings=RetrySettings{totalTimeout=PT1M, 
initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT0S, maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, 
rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, createAppProfileSettings=UnaryCallSettings{retryableCodes=[], 
retrySettings=RetrySettings{totalTimeout=PT1M, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT0S, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
getAppProfileSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
listAppProfilesSettings=PagedCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
updateAppProfileSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
updateAppProfileOperationSettings=com.google.api.gax.rpc.OperationCallSettings@60f82f98, 
deleteAppProfileSettings=UnaryCallSettings{retryableCodes=[], retrySettings=RetrySettings{totalTimeout=PT1M, 
initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT0S, maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, 
rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, getIamPolicySettings=UnaryCallSettings{retryableCodes=
[DEADLINE_EXCEEDED, UNAVAILABLE], retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, 
retryDelayMultiplier=2.0, maxRetryDelay=PT1M, maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, 
rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, setIamPolicySettings=UnaryCallSettings{retryableCodes=[], 
retrySettings=RetrySettings{totalTimeout=PT1M, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT0S, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
testIamPermissionsSettings=UnaryCallSettings{retryableCodes=[DEADLINE_EXCEEDED, UNAVAILABLE], 
retrySettings=RetrySettings{totalTimeout=PT10M, initialRetryDelay=PT1S, retryDelayMultiplier=2.0, maxRetryDelay=PT1M, 
maxAttempts=0, jittered=true, initialRpcTimeout=PT1M, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT1M}}, 
stubSettings=BigtableInstanceAdminStubSettings{executorProvider=InstantiatingExecutorProvider{executorThreadCount=4, 
threadFactory=com.google.api.gax.core.InstantiatingExecutorProvider$1@35f983a6}, 
transportChannelProvider=com.google.api.gax.grpc.InstantiatingGrpcChannelProvider@7f690630, 
credentialsProvider=GoogleCredentialsProvider{scopesToApply=[https://www.googleapis.com/auth/bigtable.admin, 
https://www.googleapis.com/auth/bigtable.admin.cluster, https://www.googleapis.com/auth/bigtable.admin.instance, 
https://www.googleapis.com/auth/bigtable.admin.table, https://www.googleapis.com/auth/cloud-bigtable.admin, 
https://www.googleapis.com/auth/cloud-bigtable.admin.cluster, https://www.googleapis.com/auth/cloud-bigtable.admin.table, 
https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only], 
jwtEnabledScopes=[], OAuth2Credentials=null}, headerProvider=com.google.api.gax.rpc.NoHeaderProvider@edf4efb, 
internalHeaderProvider=com.google.api.gax.rpc.ApiClientHeaderProvider@2f7a2457, 
clock=com.google.api.core.NanoClock@566776ad, endpoint=bigtableadmin.googleapis.com:443, quotaProjectId=null, 
streamWatchdogProvider=com.google.api.gax.rpc.InstantiatingWatchdogProvider@6108b2d7, 
streamWatchdogCheckInterval=PT10S, tracerFactory=com.google.api.gax.tracing.NoopApiTracerFactory@1554909b}}

```
Fixes #233

2020-10-22 15:20 UTC, igorbernstein2 commented
This looks mostly good. As a follow up, can you open a PR in gax to add meaningful toString impl for:
- InstantiatingExecutorProvider
- OperationCallSettings
- InstantiatingGrpcChannelProvider
- NoHeaderProvider
- InstantiatingWatchdogProvider
- etc

2020-10-22 15:45 UTC, dmitry-fa commented
@igorbernstein2 the issue filed: https://github.com/googleapis/gax-java/issues/1228

2020-10-22 18:53 UTC, igorbernstein2 commented
Please rebase and I'll merge the PR

2020-10-22 21:44 UTC, kolea2 requested changes

2020-10-22 21:44 UTC, kolea2 commented on google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminSettings.java
to be reviewed

2020-10-23 09:03 UTC, dmitry-fa commented
> 
> 
> Please rebase and I'll merge the PR

done

2020-10-23 20:34 UTC, igorbernstein2 approved these changes

2020-10-23 20:34 UTC, merged