fix: filter limit constant
googleapis/java-bigtable pull request #787
Opened 2021-04-27 19:32 UTC by igorbernstein2

Should  be 20 KB not 20 MB
https://cloud.google.com/bigtable/quotas#row-filters

2021-04-27 20:40 UTC, mutianf approved these changes
LGTM

2021-04-28 21:29 UTC, mutianf requested changes
Looks like the test also needs to be updated:

```
[INFO] Running com.google.cloud.bigtable.data.v2.models.QueryTest
Error:  Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.579 s <<< FAILURE! - in com.google.cloud.bigtable.data.v2.models.QueryTest
Error:  com.google.cloud.bigtable.data.v2.models.QueryTest.filterTestWithExceptions  Time elapsed: 0.563 s  <<< FAILURE!
value of           : throwable.getMessage()
expected to contain: filter size can't be more than 20MB
but was            : filter size can't be more than 20KB
	at com.google.cloud.bigtable.data.v2.models.QueryTest.filterTestWithExceptions(QueryTest.java:134)
Caused by: java.lang.IllegalArgumentException: filter size can't be more than 20KB
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:144)
	at com.google.cloud.bigtable.data.v2.models.Query.filter(Query.java:172)
```

2021-05-05 19:29 UTC, kolea2 approved these changes

2021-05-05 20:46 UTC, mutianf approved these changes

2021-05-07 14:43 UTC, merged